
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action SaveAction;
	private global::Gtk.Action ProjectAction;
	private global::Gtk.Action OpenAction;
	private global::Gtk.Action SaveAction1;
	private global::Gtk.Action openAction;
	private global::Gtk.Action FileAction1;
	private global::Gtk.Action openAction1;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action quitAction1;
	private global::Gtk.Action SaveAsAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action AskForHelpAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.Action ExportAction;
	private global::Gtk.Action Action;
	private global::Gtk.Action convertAction;
	private global::Gtk.Action CSVAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.HBox hbox2;
	private global::PromoterTool.EmailsWidget mEmailWidget;
	private global::Gtk.Statusbar statusbar1;
	private global::Gtk.Label label15;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.ProjectAction = new global::Gtk.Action ("ProjectAction", global::Mono.Unix.Catalog.GetString ("Project"), null, null);
		this.ProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Project");
		w1.Add (this.ProjectAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.SaveAction1 = new global::Gtk.Action ("SaveAction1", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction1, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.openAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.openAction1, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.saveAction, null);
		this.quitAction1 = new global::Gtk.Action ("quitAction1", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction1, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", global::Mono.Unix.Catalog.GetString ("Save As"), null, null);
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As");
		w1.Add (this.SaveAsAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AskForHelpAction = new global::Gtk.Action ("AskForHelpAction", global::Mono.Unix.Catalog.GetString ("Ask For Help"), null, null);
		this.AskForHelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ask For Help");
		w1.Add (this.AskForHelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.ExportAction = new global::Gtk.Action ("ExportAction", global::Mono.Unix.Catalog.GetString ("Export"), null, null);
		this.ExportAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Export");
		w1.Add (this.ExportAction, null);
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("__________________"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("__________________");
		w1.Add (this.Action, null);
		this.convertAction = new global::Gtk.Action ("convertAction", global::Mono.Unix.Catalog.GetString ("Export.."), null, "gtk-convert");
		this.convertAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Export..");
		w1.Add (this.convertAction, null);
		this.CSVAction = new global::Gtk.Action ("CSVAction", global::Mono.Unix.Catalog.GetString ("CSV"), null, null);
		this.CSVAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("CSV");
		w1.Add (this.CSVAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Email Scavenger - by Red Blue Software");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./favicon.ico"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction1' action='FileAction1'><menuitem name='quitAction1' action='quitAction1'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AskForHelpAction' action='AskForHelpAction'/><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		this.hbox2.BorderWidth = ((uint)(6));
		// Container child hbox2.Gtk.Box+BoxChild
		this.mEmailWidget = new global::PromoterTool.EmailsWidget ();
		this.mEmailWidget.Events = ((global::Gdk.EventMask)(256));
		this.mEmailWidget.Name = "mEmailWidget";
		this.hbox2.Add (this.mEmailWidget);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.mEmailWidget]));
		w3.Position = 0;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w4.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.WidthRequest = 150;
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Email Scavenger");
		this.statusbar1.Add (this.label15);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.label15]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 714;
		this.DefaultHeight = 619;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SaveAction1.Activated += new global::System.EventHandler (this.OnSave);
		this.openAction1.Activated += new global::System.EventHandler (this.OnFileOpen);
		this.saveAction.Activated += new global::System.EventHandler (this.OnFileSave);
		this.quitAction1.Activated += new global::System.EventHandler (this.OnFileQuit);
		this.SaveAsAction.Activated += new global::System.EventHandler (this.OnFileSaveAs);
		this.AskForHelpAction.Activated += new global::System.EventHandler (this.OnHelpOpenClicked);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutClicked);
	}
}
