
// This file has been generated by the GUI designer. Do not modify.
namespace PromoterTool
{
	public partial class CompetitionWidget
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Entry mSearchTerm;
		private global::Gtk.Button button110;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView mSearchResults;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PromoterTool.CompetitionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PromoterTool.CompetitionWidget";
			// Container child PromoterTool.CompetitionWidget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Search Term:");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.mSearchTerm = new global::Gtk.Entry ();
			this.mSearchTerm.CanFocus = true;
			this.mSearchTerm.Name = "mSearchTerm";
			this.mSearchTerm.IsEditable = true;
			this.mSearchTerm.InvisibleChar = '•';
			this.hbox3.Add (this.mSearchTerm);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.mSearchTerm]));
			w3.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button110 = new global::Gtk.Button ();
			this.button110.WidthRequest = 100;
			this.button110.CanFocus = true;
			this.button110.Name = "button110";
			this.button110.UseUnderline = true;
			this.button110.Label = global::Mono.Unix.Catalog.GetString ("Search");
			this.hbox3.Add (this.button110);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button110]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.mSearchResults = new global::Gtk.TreeView ();
			this.mSearchResults.CanFocus = true;
			this.mSearchResults.Name = "mSearchResults";
			this.GtkScrolledWindow.Add (this.mSearchResults);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w7.Position = 3;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
