
// This file has been generated by the GUI designer. Do not modify.
namespace PromoterTool
{
	public partial class RankTracker
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PromoterTool.RankTracker
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PromoterTool.RankTracker";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
