
// This file has been generated by the GUI designer. Do not modify.
namespace PromoterTool
{
	public partial class EmailsWidget
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Entry mSearchQuery;
		private global::Gtk.Button mBtnSearch;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label4;
		private global::Gtk.HScale mScaleNumPages;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label label1;
		private global::Gtk.HScale mScaleDepth;
		private global::Gtk.CheckButton mCheckSingleDomain;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Label label5;
		private global::Gtk.Entry mEntryCampaignName;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label label7;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView mEmailList;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label9;
		private global::Gtk.ProgressBar mProgress;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label6;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Button mBtnCSV;
		private global::Gtk.Button mBtnClear;
		private global::Gtk.CheckButton mCheckLatestOnly;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label label10;
		private global::Gtk.ComboBox mComboFilterCat;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.Entry mStatus;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label8;
		private global::Gtk.Label mResultTotal;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView mEmailResults;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PromoterTool.EmailsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PromoterTool.EmailsWidget";
			// Container child PromoterTool.EmailsWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter google search query or a URL to scan x levels deep:");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.mSearchQuery = new global::Gtk.Entry ();
			this.mSearchQuery.CanFocus = true;
			this.mSearchQuery.Name = "mSearchQuery";
			this.mSearchQuery.IsEditable = true;
			this.mSearchQuery.InvisibleChar = '•';
			this.hbox2.Add (this.mSearchQuery);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.mSearchQuery]));
			w3.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.mBtnSearch = new global::Gtk.Button ();
			this.mBtnSearch.WidthRequest = 150;
			this.mBtnSearch.CanDefault = true;
			this.mBtnSearch.CanFocus = true;
			this.mBtnSearch.Name = "mBtnSearch";
			this.mBtnSearch.UseUnderline = true;
			this.mBtnSearch.Label = global::Mono.Unix.Catalog.GetString ("Find Emails");
			this.hbox2.Add (this.mBtnSearch);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.mBtnSearch]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Pages of search results to scan:");
			this.vbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mScaleNumPages = new global::Gtk.HScale (null);
			this.mScaleNumPages.CanFocus = true;
			this.mScaleNumPages.Name = "mScaleNumPages";
			this.mScaleNumPages.Adjustment.Lower = 1;
			this.mScaleNumPages.Adjustment.Upper = 10;
			this.mScaleNumPages.Adjustment.PageIncrement = 1;
			this.mScaleNumPages.Adjustment.StepIncrement = 1;
			this.mScaleNumPages.Adjustment.Value = 3;
			this.mScaleNumPages.DrawValue = true;
			this.mScaleNumPages.Digits = 0;
			this.mScaleNumPages.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox4.Add (this.mScaleNumPages);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mScaleNumPages]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Depth of search (in levels):");
			this.hbox11.Add (this.label1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox4.Add (this.hbox11);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox11]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mScaleDepth = new global::Gtk.HScale (null);
			this.mScaleDepth.CanFocus = true;
			this.mScaleDepth.Name = "mScaleDepth";
			this.mScaleDepth.Adjustment.Upper = 10;
			this.mScaleDepth.Adjustment.PageIncrement = 1;
			this.mScaleDepth.Adjustment.PageSize = 2;
			this.mScaleDepth.Adjustment.StepIncrement = 1;
			this.mScaleDepth.DrawValue = true;
			this.mScaleDepth.Digits = 0;
			this.mScaleDepth.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox4.Add (this.mScaleDepth);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mScaleDepth]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mCheckSingleDomain = new global::Gtk.CheckButton ();
			this.mCheckSingleDomain.CanFocus = true;
			this.mCheckSingleDomain.Name = "mCheckSingleDomain";
			this.mCheckSingleDomain.Label = global::Mono.Unix.Catalog.GetString ("Restrict to query domain.");
			this.mCheckSingleDomain.Active = true;
			this.mCheckSingleDomain.DrawIndicator = true;
			this.mCheckSingleDomain.UseUnderline = true;
			this.vbox4.Add (this.mCheckSingleDomain);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mCheckSingleDomain]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Tag for current search:");
			this.hbox10.Add (this.label5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label5]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox4.Add (this.hbox10);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox10]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mEntryCampaignName = new global::Gtk.Entry ();
			this.mEntryCampaignName.CanFocus = true;
			this.mEntryCampaignName.Name = "mEntryCampaignName";
			this.mEntryCampaignName.Text = global::Mono.Unix.Catalog.GetString ("Default");
			this.mEntryCampaignName.IsEditable = true;
			this.mEntryCampaignName.InvisibleChar = '•';
			this.vbox4.Add (this.mEntryCampaignName);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mEntryCampaignName]));
			w14.Position = 6;
			w14.Expand = false;
			w14.Fill = false;
			this.GtkAlignment.Add (this.vbox4);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Search Settings</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.hbox4.Add (this.frame1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame1]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("List of emails (copy paste anywhere you like):");
			this.hbox7.Add (this.label7);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label7]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox5.Add (this.hbox7);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox7]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.mEmailList = new global::Gtk.TextView ();
			this.mEmailList.CanFocus = true;
			this.mEmailList.Name = "mEmailList";
			this.mEmailList.Editable = false;
			this.mEmailList.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add (this.mEmailList);
			this.vbox5.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow1]));
			w21.Position = 1;
			this.hbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox5]));
			w22.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("progress");
			this.vbox6.Add (this.label9);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label9]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.mProgress = new global::Gtk.ProgressBar ();
			this.mProgress.Name = "mProgress";
			this.vbox6.Add (this.mProgress);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.mProgress]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Export results list:");
			this.hbox6.Add (this.label6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label6]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox6.Add (this.hbox6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.mBtnCSV = new global::Gtk.Button ();
			this.mBtnCSV.CanFocus = true;
			this.mBtnCSV.Name = "mBtnCSV";
			this.mBtnCSV.UseUnderline = true;
			this.mBtnCSV.Label = global::Mono.Unix.Catalog.GetString ("Export CSV");
			this.hbox5.Add (this.mBtnCSV);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.mBtnCSV]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.mBtnClear = new global::Gtk.Button ();
			this.mBtnClear.CanFocus = true;
			this.mBtnClear.Name = "mBtnClear";
			this.mBtnClear.UseUnderline = true;
			this.mBtnClear.Label = global::Mono.Unix.Catalog.GetString ("Clear Results");
			this.hbox5.Add (this.mBtnClear);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.mBtnClear]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox6.Add (this.hbox5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.mCheckLatestOnly = new global::Gtk.CheckButton ();
			this.mCheckLatestOnly.CanFocus = true;
			this.mCheckLatestOnly.Name = "mCheckLatestOnly";
			this.mCheckLatestOnly.Label = global::Mono.Unix.Catalog.GetString ("Show latest search only");
			this.mCheckLatestOnly.DrawIndicator = true;
			this.mCheckLatestOnly.UseUnderline = true;
			this.vbox6.Add (this.mCheckLatestOnly);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.mCheckLatestOnly]));
			w30.Position = 4;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Filter results:");
			this.hbox9.Add (this.label10);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label10]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox6.Add (this.hbox9);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox9]));
			w32.Position = 5;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.mComboFilterCat = global::Gtk.ComboBox.NewText ();
			this.mComboFilterCat.Name = "mComboFilterCat";
			this.vbox6.Add (this.mComboFilterCat);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.mComboFilterCat]));
			w33.Position = 6;
			w33.Expand = false;
			w33.Fill = false;
			this.GtkAlignment1.Add (this.vbox6);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Results Settings</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel7;
			this.hbox4.Add (this.frame2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame2]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.mStatus = new global::Gtk.Entry ();
			this.mStatus.CanFocus = true;
			this.mStatus.Name = "mStatus";
			this.mStatus.Text = global::Mono.Unix.Catalog.GetString ("Status...");
			this.mStatus.IsEditable = false;
			this.mStatus.InvisibleChar = '•';
			this.vbox2.Add (this.mStatus);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.mStatus]));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("List of gathered results:");
			this.hbox8.Add (this.label8);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label8]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.mResultTotal = new global::Gtk.Label ();
			this.mResultTotal.Name = "mResultTotal";
			this.mResultTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("(0)");
			this.hbox8.Add (this.mResultTotal);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.mResultTotal]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox2.Add (this.hbox8);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
			w41.Position = 4;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.mEmailResults = new global::Gtk.TreeView ();
			this.mEmailResults.CanFocus = true;
			this.mEmailResults.Name = "mEmailResults";
			this.GtkScrolledWindow.Add (this.mEmailResults);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w43.Position = 5;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.mSearchQuery.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.onSearchKeyPress);
			this.mBtnSearch.Clicked += new global::System.EventHandler (this.onSearchClicked);
			this.mBtnCSV.Clicked += new global::System.EventHandler (this.onExportCsvClicked);
			this.mBtnClear.Clicked += new global::System.EventHandler (this.onClearResultsClicked);
			this.mCheckLatestOnly.Clicked += new global::System.EventHandler (this.onLatestQueryClicked);
			this.mComboFilterCat.Changed += new global::System.EventHandler (this.onRecordTypeChanged);
		}
	}
}
