
// This file has been generated by the GUI designer. Do not modify.
namespace PromoterTool
{
	public partial class GoogleChooser
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label1;
		private global::Gtk.ComboBoxEntry mGoogleLocale;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PromoterTool.GoogleChooser
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PromoterTool.GoogleChooser";
			// Container child PromoterTool.GoogleChooser.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Which Google:");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.mGoogleLocale = global::Gtk.ComboBoxEntry.NewText ();
			this.mGoogleLocale.AppendText (global::Mono.Unix.Catalog.GetString ("com"));
			this.mGoogleLocale.AppendText (global::Mono.Unix.Catalog.GetString ("se"));
			this.mGoogleLocale.AppendText (global::Mono.Unix.Catalog.GetString ("co.uk"));
			this.mGoogleLocale.Name = "mGoogleLocale";
			this.mGoogleLocale.Active = 0;
			this.vbox2.Add (this.mGoogleLocale);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.mGoogleLocale]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
