
// This file has been generated by the GUI designer. Do not modify.
namespace PromoterTool
{
	public partial class RankingsWidget
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView mKeywords;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label1;
		private global::Gtk.HScale mSearchDepth;
		private global::PromoterTool.GoogleChooser mLocale;
		private global::Gtk.Button mButtonUpdate;
		private global::Gtk.ProgressBar mProgress;
		private global::Gtk.Button mSaveButton;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView mDomains;
		private global::Gtk.Label GtkLabel1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView mRankTreeView;
		private global::Gtk.Frame mPlotBox;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.HBox mPlotContainer;
		private global::Gtk.Label GtkLabel4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PromoterTool.RankingsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PromoterTool.RankingsWidget";
			// Container child PromoterTool.RankingsWidget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(6));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.mKeywords = new global::Gtk.TextView ();
			this.mKeywords.CanFocus = true;
			this.mKeywords.Name = "mKeywords";
			this.GtkScrolledWindow1.Add (this.mKeywords);
			this.GtkAlignment.Add (this.GtkScrolledWindow1);
			this.frame3.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Keywords (one per line)</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel2;
			this.hbox3.Add (this.frame3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.frame3]));
			w4.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Search Depth");
			this.vbox4.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mSearchDepth = new global::Gtk.HScale (null);
			this.mSearchDepth.CanFocus = true;
			this.mSearchDepth.Name = "mSearchDepth";
			this.mSearchDepth.Adjustment.Lower = 1;
			this.mSearchDepth.Adjustment.Upper = 5;
			this.mSearchDepth.Adjustment.PageIncrement = 1;
			this.mSearchDepth.Adjustment.StepIncrement = 1;
			this.mSearchDepth.Adjustment.Value = 2;
			this.mSearchDepth.DrawValue = true;
			this.mSearchDepth.Digits = 0;
			this.mSearchDepth.ValuePos = ((global::Gtk.PositionType)(1));
			this.vbox4.Add (this.mSearchDepth);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mSearchDepth]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mLocale = new global::PromoterTool.GoogleChooser ();
			this.mLocale.Events = ((global::Gdk.EventMask)(256));
			this.mLocale.Name = "mLocale";
			this.vbox4.Add (this.mLocale);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mLocale]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mButtonUpdate = new global::Gtk.Button ();
			this.mButtonUpdate.CanFocus = true;
			this.mButtonUpdate.Name = "mButtonUpdate";
			this.mButtonUpdate.UseUnderline = true;
			this.mButtonUpdate.Label = global::Mono.Unix.Catalog.GetString ("Update Ranks");
			this.vbox4.Add (this.mButtonUpdate);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mButtonUpdate]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mProgress = new global::Gtk.ProgressBar ();
			this.mProgress.WidthRequest = 100;
			this.mProgress.HeightRequest = 10;
			this.mProgress.Name = "mProgress";
			this.vbox4.Add (this.mProgress);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mProgress]));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.mSaveButton = new global::Gtk.Button ();
			this.mSaveButton.CanFocus = true;
			this.mSaveButton.Name = "mSaveButton";
			this.mSaveButton.UseUnderline = true;
			this.mSaveButton.Label = global::Mono.Unix.Catalog.GetString ("Save Results");
			this.vbox4.Add (this.mSaveButton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.mSaveButton]));
			w10.Position = 5;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.mDomains = new global::Gtk.TextView ();
			this.mDomains.CanFocus = true;
			this.mDomains.Name = "mDomains";
			this.GtkScrolledWindow2.Add (this.mDomains);
			this.GtkAlignment1.Add (this.GtkScrolledWindow2);
			this.frame4.Add (this.GtkAlignment1);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>URLs (one per line)</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel1;
			this.hbox3.Add (this.frame4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.frame4]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 2;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w16.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.mRankTreeView = new global::Gtk.TreeView ();
			this.mRankTreeView.HeightRequest = 100;
			this.mRankTreeView.CanFocus = true;
			this.mRankTreeView.Name = "mRankTreeView";
			this.GtkScrolledWindow.Add (this.mRankTreeView);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w18.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.mPlotBox = new global::Gtk.Frame ();
			this.mPlotBox.HeightRequest = 150;
			this.mPlotBox.Name = "mPlotBox";
			this.mPlotBox.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child mPlotBox.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.mPlotContainer = new global::Gtk.HBox ();
			this.mPlotContainer.Name = "mPlotContainer";
			this.mPlotContainer.Spacing = 6;
			this.GtkAlignment2.Add (this.mPlotContainer);
			this.mPlotBox.Add (this.GtkAlignment2);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("Ranking Graph:");
			this.GtkLabel4.UseMarkup = true;
			this.mPlotBox.LabelWidget = this.GtkLabel4;
			this.vbox3.Add (this.mPlotBox);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.mPlotBox]));
			w21.Position = 2;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.mButtonUpdate.Clicked += new global::System.EventHandler (this.OnUpdateClicked);
			this.mSaveButton.Clicked += new global::System.EventHandler (this.onSaveResultsClicked);
		}
	}
}
